### ISSUE TITLE
Sensorless homing not working

### ISSUE THREAD

**Issue by bartolomeus** [makerbase-mks/MKS-TMC2209#1]
MKS SGEN L
MKS TMC2209 drivers
Marlin 2.0

Compiled firmware, with sensorless homing enabled. Compiled without erros.
Uploaded to the board, but Sensorless homing does not work. Changing sensitivity settings has no effect. Motors do not move at all after a homing command.

Is there a guide to get these drivers to work with sensorless homing?

**Comment by makerbase-mks** [comment]
At present, the use of Sensorless homing in the TMC2209 does have many uncertainties, and Marlin's firmware needs to be further optimized to a large extent. MKS will test it and follow up new Marlin firmware ...

**Comment by makerbase-mks** [comment]
Use Sensorless homing function
1. MKS SGEN_L Drive IC Power select 3.3V
![image](https://user-images.githubusercontent.com/12979070/76481537-b67a9380-644c-11ea-92f4-e1e0e437a905.png)
2. Marlin firmware enable drive type TMC2209
![image](https://user-images.githubusercontent.com/12979070/76481455-8501c800-644c-11ea-9b4c-c356ee6643ee.png)
3. configuration_adv.h enable SENSORLESS_HOMING 
![image](https://user-images.githubusercontent.com/12979070/76481835-7a93fe00-644d-11ea-812e-6d7a8a50db44.png)

**Comment by makerbase-mks** [comment]
But you need change hardware, you need flying lead leads the DIAG signal to the S end of the limit,
MKS TMC2209 V1.0
![image](https://user-images.githubusercontent.com/12979070/76482157-5127a200-644e-11ea-872d-d7b6f93814e7.png)

We has chang MKS TMC2209 hardware, also have MKS TMC2209 V2.0, V2.0 can be used after plugging in, no flying lead required.
![image](https://user-images.githubusercontent.com/12979070/76482263-a2379600-644e-11ea-9635-5d2367128db5.png)
